/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*  "Docs": [{type: 'autogenerated', dirName: '.'}], */
  Build: [
    {
      type: "category",
      label: "Building with templates (IBCS)",
      items: [
        "build/build-template/ibcs",
        "build/build-template/spreadsheet",
        "build/build-template/financial",
      ],
    },
    {
      type: "category",
      label: "Format the Report",
      items: [
        "build/format/font-color-alignment",
        "build/format/display",
        "build/format/conditional-formatting",
      ],
        },
        {
            type: "category",
            label: "Edit data with tools",
            items: [
                "build/edit-data/edit-cell",
              "build/edit-data/insert-cols",
                "build/format/formula-list",
                "build/edit-data/sign",
            ],
    },
    "build/header-footer",
    "build/pagination-breaks",
    "build/notes",
    "build/reset",
    "build/audit",
    "build/charts",
    ],
    Analyze: {
        "Analyze with Inforiver": [
            "analyze/smart-analysis",
            "analyze/filters",
            "analyze/top",
            "analyze/kpi",
            "analyze/search",
            "analyze/total",
        ],
    },
    Features: {
        "Inforiver Features (Tools)": [
            "features/navigation",
            "features/managing-cols",
            "features/responsive-toolbar",
        ],
    },
    Static: {
        "Static Reports with Inforiver": [
            "static/pdf",
            "static/excel",
            "static/settings",
        ],
    },
  Docs: {
    Features: [
      "export",
      "import",
      "shortcut",
      "formula-sum",
      "col-references",
    ],
  },
  // But you can create a sidebar manually
  /*
  functionSideBar: {
        "Formula Syntax": ["formula-list"],
        "Logical Functions": [
            "references/formulas/if",
            "references/formulas/switch",
            "references/formulas/and",
            "references/formulas/or",
            "references/formulas/not",
            "references/formulas/xor",
            "references/formulas/isnumber",
            "references/formulas/ifna",
            "references/formulas/in",
        ],
        "Text Formatting Functions": [
            "references/formulas/text",
            "references/formulas/concatenate",
        ],
        "Math Functions": [
            "references/formulas/sum",
            "references/formulas/average",
            "references/formulas/averageexzero",
            "references/formulas/averageexneg",
            "references/formulas/averageexzeroneg",
            "references/formulas/countif",
            "references/formulas/abs",
            "references/formulas/min",
            "references/formulas/max",
            "references/formulas/power",
            "references/formulas/sqrt",
            "references/formulas/exp",
            "references/formulas/log",
            "references/formulas/round",
            "references/formulas/ceiling",
            "references/formulas/floor",
        ],   
},
*/
  Writeback: [
    {
      type: "category",
      label: "Writeback",
      items: ["writeback/overview", "writeback/database", "writeback/csv"],
    },
    "writeback/writeback-logs",
  ],
  Back: [
    {
      type: "category",
      label: "Writeback",
      items: ["back/overview", "back/csv"],
    },
    "back/writeback-logs",
    "back/database", 
  ],
};
